# Starter pipeline
trigger:
  - main

variables:
  imageName: 'gcr.io/datamechanics/custom/testazdevops'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: ./Dockerfile
