# Starter pipeline
trigger:
  - main

variables:
  imageName: 'vjolivet/bzh'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: ./Dockerfile
    containerRegistry: dockerhubvjolivet
