# Starter pipeline

trigger:
- main

pool:
  vmImage: 'ubuntu-1604' # set to windows-latest or another Windows vmImage for Windows builds

variables:
  imageName: 'pipelines-javascript-docker'

steps:
  task: Docker@2
  displayName: Build an image
  inputs:
    repository: gcr.io/datamechanics/custom/test
    command: build
    Dockerfile: ./Dockerfile
