# Starter pipeline
trigger:
  - main

pool:
  vmImage: 'alpine' # set to windows-latest or another Windows vmImage for Windows builds

variables:
  imageName: 'testazdevopspipe'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: ./Dockerfile
