# Starter pipeline
trigger:
  - main

variables:
  imageName: 'testazdevopspipe'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: ./Dockerfile
